Aguafrommars/TheIdServer

- test/Aguacongas.TheIdServer.Authentication..Integration.Test/appsettings.Test.json
- test/Aguacongas.TheIdServer.IntegrationTest/appsettings.Test.json
> test: reduce test log level

- src/Aguacongas.TheIdServer/Startup.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Extensions/IdentityServerBuilderExtensions.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Models/ClientRegisteration.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Models/LocalizableProperty.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/RegisterController.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Services/ClientRegisterationConverter.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Services/IRegisterClientService.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Services/RegisterClientService.cs
- test/Aguacongas.IdentityServer.Admin.Test/Services/ClientRegisterationConverterTest.cs
- test/Aguacongas.TheIdServer.IntegrationTest/Controlers/RegisterControllerTest.cs
> feat: dynamic client registration

- CONTRIBUTING.md
- README.md
- doc/API.md
- doc/CLAIMS_PROVIDER.md
- doc/CLIENT.md
- doc/EXPORT_IMPORT.md
- doc/IDENTITY.md
- doc/LOCALIZATION.md
- doc/PROVIDER.md
- doc/ROLE.md
- doc/SCOPE.md
- doc/USER.md
- src/Aguacongas.TheIdServer.BlazorApp/README.md
- src/Aguacongas.TheIdServer/README.md
This is first PR to the project.  It consists of a minor documentation corrections.  I corrected some minor typos, spelling and English grammar.  I also updated image links to be consistent, as some of the links were not relative paths which causes issues with offline Markdown previews.
> Minor documentation corrections

- README.md
- src/Aguacongas.TheIdServer/README.md
- src/Aguacongas.TheIdServer/appsettings.Azure.json
- src/Aguacongas.TheIdServer/appsettings.json
Update readme files for server configuration and OIDC conformance tests
> docs: update readme

- src/Aguacongas.TheIdServer/Quickstart/Account/ExternalController.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Components/LoginDisplay.razor.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Extensions/MvcBuilderExtensions.cs
> fix: external login

- src/Aguacongas.TheIdServer.BlazorApp/App.razor.cs
- src/Aguacongas.TheIdServer/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
- src/Aguacongas.TheIdServer/Areas/Identity/Services/EmailApiSender.cs
- src/Aguacongas.TheIdServer/Program.cs
- src/Aguacongas.TheIdServer/Quickstart/Account/LoginViewModel.cs
- src/Aguacongas.TheIdServer/Services/PreRenderStringLocalizer.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Components/EntityInfo.razor.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Infrastructure/Abstraction/EntitiesModel.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Users/Users.razor.cs
- test/Aguacongas.TheIdServer.IntegrationTest/BlazorApp/Pages/UserTest.cs
> fix: path with user is reserved

- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.User/User.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.User/User.razor.cs
> build: add missing files to sc

- src/Aguacongas.TheIdServer/Startup.cs
> fix: set valid audience

- sample/Kubernetes/TheIdServer-public-configmap.yaml
- src/Aguacongas.TheIdServer/Extensions/DataProtectionBuilderExtentions.cs
- src/Aguacongas.TheIdServer/Extensions/IdentityServerBuilderExtensions.cs
- src/Aguacongas.TheIdServer/Models/DataProtectionOptions.cs
- test/Aguacongas.TheIdServer.Test/StartupTest.cs
> fix: storage kind filesystem typo

- src/IdentityServer/Aguacongas.IdentityServer.EntityFramework.Store/IdentityServerStores/CorsPolicyService.cs
- src/IdentityServer/Aguacongas.IdentityServer.RavenDb.Store/Extensions/GetRequestExtensions.cs
- test/Aguacongas.IdentityServer.RavenDb.Store.Test/AdminStores/AdminStoreTest.cs
> fix: request on datetime

- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Components/EntitesGridModel.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Client.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Client.razor.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/ClientScope.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/ClientScope.razor.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/ClientUris.razor.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/ClientUrisPanel.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/ClientUrisPanel.razor.cs
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/IdentityProvider.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Pages.Client/Components/IdentityProvider.razor.cs
- src/IdentityServer/Aguacongas.IdentityServer.RavenDb.Store/AdminStores/AdminStore.cs
- src/IdentityServer/Aguacongas.IdentityServer.RavenDb.Store/Extensions/ServiceCollectionExtensions.cs
- test/Aguacongas.TheIdServer.IntegrationTest/BlazorApp/Pages/ClientTest.cs
> fix: client settings lost on save in UI

- src/Aguacongas.TheIdServer.BlazorApp/Shared/NavMenu.razor
- src/Aguacongas.TheIdServer.BlazorApp/wwwroot/css/app.css
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Components/LoginDisplay.razor
- src/BlazorApp/Aguacongas.TheIdServer.BlazorApp.Components/LoginDisplay.razor.cs
> fix: login & register link invisible on mobilde

- src/Aguacongas.TheIdServer/Startup.cs
> fix: export doesn't work with ref token

- src/Aguacongas.TheIdServer/Startup.cs
> refactor: add default token query string

- src/Aguacongas.TheIdServer/Startup.cs
- src/IdentityServer/Aguacongas.IdentityServer.Admin/Services/OneTimeTokenService.cs
- src/IdentityServer/Aguacongas.IdentityServer/Abstractions/IRetrieveOneTimeToken.cs
> fix: export with JWT token

- src/IdentityServer/Aguacongas.IdentityServer/Extensions/EntityExtension.cs
> fix: reliying party encryption certificate not saved

- src/Aguacongas.TheIdServer.Duende/README.md
- src/IdentityServer/Aguacongas.IdentityServer.WsFederation/Aguacongas.IdentityServer.WsFederation.csproj
- src/IdentityServer/Aguacongas.IdentityServer/Aguacongas.IdentityServer.csproj
introduce in Microsoft.AspNetCore.Mvc@2.2.0
https://app.snyk.io/org/aguacongas/project/13301f5e-fe26-46c2-a0f2-807fa36590c4
> fix security issue

- src/Aguacongas.TheIdServer/Areas/Identity/Pages/Account/Register.cshtml
> Fixed Register page input component issue

- src/Aguacongas.TheIdServer.Duende/Extensions/ApplicationBuilderExtensions.cs
- src/IdentityServer/Duende/Aguacongas.IdentityServer.Duende/Extensions/UserSessionExtensions.cs
- test/Duende/Aguacongas.IdentityServer.Duende.Test/Store/ServerSideSessionStoreTest.cs
> fix: unable to login using postgreSQL

- src/IdentityServer/Aguacongas.IdentityServer.Admin/Aguacongas.IdentityServer.Admin.csproj
- src/IdentityServer/Aguacongas.IdentityServer.EntityFramework.Store/Extensions/QueryableExtensions.cs
- src/IdentityServer/Aguacongas.IdentityServer.MongoDb.Store/AdminStores/AdminStore.cs
- src/IdentityServer/Aguacongas.IdentityServer.RavenDb.Store/Extensions/GetRequestExtensions.cs
- src/IdentityServer/Aguacongas.IdentityServer/Aguacongas.IdentityServer.csproj
- test/Duende/Aguacongas.TheIdServer.Integration.Duende.Test/Controllers/RegisterControllerTest.cs
feat: replace Community.OData.Linq by OData2Linq
> feat: replace Community.OData.Linq by OData2Linq
